export const SWITCH_NAV_TYPE = "SWITCH_NAV_TYPE";

export const UPDATE_HOT_IMAGES = "UPDATE_HOT_IMAGES";
export const UPDATE_THEMES = "UPDATE_THEMES";
export const UPDATE_IMAGES = "UPDATE_IMAGES";

export const CLEAR_IMAGES = "CLEAR_IMAGES";

export const SWITCH_CUSTOMIZE_TAB = "SWITCH_CUSTOMIZE_TAB";
export const CHANGE_CLOTH_TYPE = "CHANGE_CLOTH_TYPE";
export const CHANGE_CLOTH_SIZE = "CHANGE_CLOTH_SIZE";
export const CHANGE_CLOTH_COLOR = "CHANGE_CLOTH_COLOR";
export const CHANGE_IMAGE_SIZE = "CHANGE_IMAGE_SIZE";
export const CHANGE_IMAGE_POSITION = "CHANGE_IMAGE_POSITION";

export const UPDATE_ORDER_INFO = "UPDATE_ORDER_INFO";
export const UPDATE_ORDER_NUMBER = "UPDATE_ORDER_NUMBER";